Try another way

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,14 +41,29 @@ jobs:
         chromedriver --url-base=/wd/hub &
         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
 
-    # - name: Install ChromeDriver
-    #   run: |
-    #     CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9\.]{2,}")
-    #     CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
-    #     curl -L -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
-    #     unzip chromedriver_linux64.zip
-    #     sudo mv chromedriver /usr/local/bin/
-    #     rm chromedriver_linux64.zip
+    - name: Install ChromeDriver
+      run: |
+          echo "Retrieving Chrome version..."
+          FULL_CHROME_VERSION=$(google-chrome --version)
+          echo "Full Chrome version: $FULL_CHROME_VERSION"
+          
+          CHROME_VERSION=$(echo $FULL_CHROME_VERSION | grep -oE "[0-9]+" | head -1)
+          echo "Chrome major version: $CHROME_VERSION"
+          
+          echo "Fetching the latest ChromeDriver version for Chrome $CHROME_VERSION..."
+          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
+          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
+          
+          if [ -z "$CHROMEDRIVER_VERSION" ]; then
+            echo "Failed to fetch ChromeDriver version!"
+            exit 1
+          fi
+          
+          echo "Downloading ChromeDriver version $CHROMEDRIVER_VERSION..."
+          curl -L -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
+          unzip chromedriver_linux64.zip
+          sudo mv chromedriver /usr/local/bin/
+          rm chromedriver_linux64.zip
 
     - name: Run end-to-end tests
       run: npm test -- tests/e2e
